name: GitHub Profile Views Counter CI - Fabiohcnobre
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  release:
    name: GitHub Profile Views Counter Action
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 14.17.0
      - name: gayanvoice - github-profile-views-counter-action
        uses: gayanvoice/github-profile-views-counter-action@3.0.0
        env:
          INSIGHTS_TOKEN: ${{ secrets.INSIGHTS_TOKEN }}
